# Generated by Django 6.0.7 on 2026-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('course', models.CharField(choices=[('Ingliz tili', 'Ingliz tili'), ('Front-end dasturlash', 'Front-end dasturlash'), ('Matematika', 'Matematika'), ('Kids English & Logic', 'Kids English & Logic'), ('Boshqa / konsultatsiya', 'Boshqa / konsultatsiya')], max_length=80, verbose_name='Kurs')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Bog‘lanildi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
