# Generated by Django 6.0.7 on 2026-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_studygroup_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.CharField(blank=True, max_length=120, verbose_name='Kurs'),
        ),
    ]
