# Generated by Django 6.0.7 on 2026-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lead_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kurs nomi')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration', models.CharField(blank=True, max_length=80, verbose_name='Davomiyligi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytda ko‘rsatish')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Bosh sarlavha')),
                ('hero_text', models.TextField(blank=True, verbose_name='Bosh matn')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('work_time', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
